services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb

  postgraphile:
    image: graphile/postgraphile
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydb
      - SCHEMA=public
      - JWT_SECRET=your-jwt-secret
